<?php
// Do not edit this file, instead use the new dashboard editor in the expert section.
// New CSS Overlay for Pi-Star, to allow setting the variables from outside this file.

// Output CSS and not plain text
header("Content-type: text/css");

// Check if the config file exists
if (file_exists('/etc/pistar-css.ini')) {
    // Use the values from the file
    $piStarCssFile = '/etc/pistar-css.ini';
	if (fopen($piStarCssFile,'r')) { $piStarCss = parse_ini_file($piStarCssFile, true); }
    
    // Set the Values from the config file
    $backgroundPage = $piStarCss['Background']['PageColor'];		// usually off-white
    $backgroundContent = $piStarCss['Background']['ContentColor'];      // The White background in the content section
    $backgroundBanners = $piStarCss['Background']['BannersColor'];      // The ubiquitous Pi-Star Red
    $backgroundNavbar = $piStarCss['Background']['NavbarColor'];        // Navbar background color
    $backgroundNavbarHover = $piStarCss['Background']['NavbarHoverColor']; // Navbar hover color
    $backgroundDropdown = $piStarCss['Background']['DropdownColor'];    // Dropdown menu background color
    $backgroundDropdownHover = $piStarCss['Background']['DropdownHoverColor']; // Dropdown hover background color

    $textBanners = $piStarCss['Text']['BannersColor'];            	// Usually white
    $textNavbar = $piStarCss['Text']['NavbarColor'];            	// Navbar text color
    $textNavbarHover = $piStarCss['Text']['NavbarHoverColor'];          // Navbar hover color
    $textDropdown = $piStarCss['Text']['DropdownColor'];            	// Dropdown menu text color
    $bannerDropShaddows = $piStarCss['Text']['BannersDropColor'];       // Banner drop shaddow colour

    $tableHeadDropShaddow = $piStarCss['Tables']['HeadDropColor'];      // Table Headder drop shaddows
    $tableRowEvenBg = $piStarCss['Tables']['BgEvenColor']; 		// Table Row BG Colour (Even)
    $tableRowOddBg = $piStarCss['Tables']['BgOddColor'];		// Table Row BG Colour (Odd)

    $textContent = $piStarCss['Content']['TextColor'];            	// Used for the section titles
} else {
    // Default values
    $backgroundPage = "#edf0f5";         // usually off-white
    $backgroundContent = "#ffffff";      // The White background in the content section
    $backgroundBanners = "#dd4b39";      // The ubiquitous Pi-Star Red
    $backgroundNavbar = "#242d31";        // Navbar background color
    $backgroundNavbarHover = "#a60000"; // Navbar hover color
    $backgroundDropdown = "#f9f9f9";    // Dropdown menu background color
    $backgroundDropdownHover = "#d0d0d0"; // Dropdown hover background color

    $textBanners = "#ffffff";            // Usually white
    $textNavbar = "#ffffff";           	// Navbar text color
    $textNavbarHover = "#ffffff";       // Navbar hover color
    $textDropdown = "#000000";          // Dropdown menu text color
    $bannerDropShaddows = "#303030";     // Banner drop shaddow colour
    $tableHeadDropShaddow = "#8b0000";   // Table Headder drop shaddows
    $textContent = "#000000";            // Used for the section titles
    $tableRowEvenBg = "#f7f7f7";		// Table Row BG Colour (Even)
    $tableRowOddBg = "#d0d0d0";		// Table Row BG Colour (Odd)
}
?>
.container {
    width: 820px;
    text-align: left;
    margin: auto;
}

body, font {
    font: 12px verdana,arial,sans-serif;
    color: #ffffff;
}

.header {
    background : <?php echo $backgroundBanners; ?>;
    text-decoration : none;
    color : <?php echo $textBanners; ?>;
    font-family : verdana, arial, sans-serif;
    text-align : left;
    padding : 5px 0px 5px 0px;
    border-radius : 10px 10px 0 0;
 }

.nav {
    float : left;
    margin : 0;
    padding : 3px 3px 3px 3px;
    width : 160px;
    background : #242d31;
    font-weight : normal;
    min-height : 100%;
}

.content {
    margin : 0 0 0 166px;
    padding : 1px 5px 5px 5px;
    color : <?php echo $textContent; ?>;
    background : <?php echo $backgroundContent; ?>;
    text-align: center;
}

.contentwide {
    padding: 5px 5px 5px 5px;
    color: <?php echo $textContent; ?>;
    background: <?php echo $backgroundContent; ?>;
    text-align: center;
}

.footer {
    background : <?php echo $backgroundBanners; ?>;
    text-decoration : none;
    color : <?php echo $textBanners; ?>;
    font-family : verdana, arial, sans-serif;
    font-size : 9px;
    text-align : center;
    padding : 10px 0 10px 0;
    border-radius : 0 0 10px 10px;
    clear : both;
}

#tail {
    height: 450px;
    width: 805px;
    overflow-y: scroll;
    overflow-x: scroll;
    color: #00ff00;
    background: #000000;
}

table {
    vertical-align: middle;
    text-align: center;
    empty-cells: show;
    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    border-collapse:collapse;
    border-color: #000000;
    border-style: solid;
    border-spacing: 4px;
    border-width: 2px;
    text-decoration: none;
    color: #ffffff;
    background: #000000;
    font-family: verdana,arial,sans-serif;
    width: 100%;
    white-space: nowrap;
}

table th {
    font-family: "Lucidia Console",Monaco,monospace;
    text-shadow: 1px 1px <?php echo $tableHeadDropShaddow; ?>;
    text-decoration: none;
    background: <?php echo $backgroundBanners; ?>;
    border: 1px solid #c0c0c0;
}

table tr:nth-child(even) {
    background: <?php echo $tableRowEvenBg; ?>;
}

table tr:nth-child(odd) {
    background: <?php echo $tableRowOddBg; ?>;
}

table td {
    color: #000000;
    font-family: "Lucidia Console",Monaco,monospace;
    text-decoration: none;
    border: 1px solid #000000;
}

body {
    background: <?php echo $backgroundPage; ?>;
    color: #000000;
}

a {
    text-decoration:none;
    
}

a:link, a:visited {
    text-decoration: none;
    color: #0000e0;
    font-weight: normal;
}

a.tooltip, a.tooltip:link, a.tooltip:visited, a.tooltip:active  {
    text-decoration: none;
    position: relative;
    color: #FFFFFF;
}

a.tooltip:hover {
    text-shadow: none;
    text-decoration: none;
    color: #FFFFFF;
    background: transparent;
}

a.tooltip span {
    text-shadow: none;
    text-decoration: none;
    display: none;
}

a.tooltip:hover span {
    text-shadow: none;
    text-decoration: none;
    display: block;
    position: absolute;
    top: 20px;
    left: 0;
    z-index: 100;
    color: #000000;
    border:1px solid #000000;
    background: #f7f7f7;
    font: 12px Verdana, sans-serif; 
    text-align: left;
    white-space: nowrap;
}

th:last-child a.tooltip:hover span {
    left: auto;
    right: 0;
}

a.tooltip span b {
    text-shadow: none;
    text-decoration: none;
    display: block;
    color: #000000;
    margin: 0;
    padding: 0;
    font-size: 12px;
    font-weight: bold;
    border: 0px;
    border-bottom: 1px solid black;
    background: #d0d0d0;
}

a.tooltip2, a.tooltip2:link, a.tooltip2:visited, a.tooltip2:active  {
    text-shadow: none;
    text-decoration: none;
    position: relative;
    font-weight: bold;
    color: #000000;
}

a.tooltip2:hover {
    text-shadow: none;
    text-decoration: none;
    color: #000000;
    background: transparent;
}

a.tooltip2 span {
    text-shadow: none;
    text-decoration: none;
    display: none;
}

a.tooltip2:hover span {
    text-shadow: none;
    text-decoration: none;
    display: block;
    position: absolute;
    top: 20px;
    left: 0;
    width: 202px;
    z-index: 100;
    color: #000000;
    border:1px solid #000000;
    background: #f7f7f7;
    font: 12px Verdana, sans-serif; 
    text-align: left;
    white-space: normal;
}

a.tooltip2 span b {
    text-shadow: none;
    text-decoration: none;
    display: block;
    color: #000000;
    margin: 0;
    padding: 0;
    font-size: 12px;
    font-weight: bold;
    border: 0px;
    border-bottom: 1px solid black;
    background: #d0d0d0;
}

ul {
    padding: 5px;
    margin: 10px 0;
    list-style: none;
    float: left;
}

ul li {
    float: left;
    display: inline; /*For ignore double margin in IE6*/
    margin: 0 10px;
}

ul li a {
    text-decoration: none;
    float:left;
    color: #999;
    cursor: pointer;
    font: 900 14px/22px "Arial", Helvetica, sans-serif;
}

ul li a span {
    margin: 0 10px 0 -10px;
    padding: 1px 8px 5px 18px;
    position: relative; /*To fix IE6 problem (not displaying)*/
    float:left;
}

ul.mmenu li a.current, ul.mmenu li a:hover {
    background: url(/images/buttonbg.png) no-repeat top right;
    color: #0d5f83;
}

ul.mmenu li a.current span, ul.mmenu li a:hover span {
    background: url(/images/buttonbg.png) no-repeat top left;
}

h1 {
    text-shadow: 2px 2px <?php echo $bannerDropShaddows; ?>;
    text-align: center;
}

/* CSS Toggle Code here */
.toggle {
    position: absolute;
    margin-left: -9999px;
    visibility: hidden;
}

.toggle + label {
    display: block;
    position: relative;
    cursor: pointer;
    outline: none;
}

input.toggle-round-flat + label {
    padding: 1px;
    width: 33px;
    height: 18px;
    background-color: #dddddd;
    border-radius: 10px;
    transition: background 0.4s;
}

input.toggle-round-flat + label:before,
input.toggle-round-flat + label:after {
    display: block;
    position: absolute;
    content: "";
}

input.toggle-round-flat + label:before {
    top: 1px;
    left: 1px;
    bottom: 1px;
    right: 1px;
    background-color: #fff;
    border-radius: 10px;
    transition: background 0.4s;
}

input.toggle-round-flat + label:after {
    top: 2px;
    left: 2px;
    bottom: 2px;
    width: 16px;
    background-color: #dddddd;
    border-radius: 12px;
    transition: margin 0.4s, background 0.4s;
}

input.toggle-round-flat:checked + label {
    background-color: <?php echo $backgroundBanners; ?>;
}

input.toggle-round-flat:checked + label:after {
    margin-left: 14px;
    background-color: <?php echo $backgroundBanners; ?>;
}

 /* put the same color as in left vertical status */
.navbar {
    overflow: hidden;
    background-color: <?php echo $backgroundNavbar; ?>;
}

/* Links inside the navbar */
.navbar a {
    float: right;
    font-family : verdana, arial, sans-serif;
    font-size: 14px;
    color: <?php echo $textNavbar; ?>;
    text-align: center;
    padding: 5px 8px;
    text-decoration: none;
}
`
.dropdown {
    float: left;
    overflow: hidden;
}

.dropdown .dropbutton {
    font-size: 14px;
    border: none;
    outline: none;
    color: <?php echo $textNavbar; ?>;
    padding: 5px 8px;
    background-color: <?php echo $backgroundNavbar; ?>;
    font-family: inherit;
    margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbutton {
    color: <?php echo $textNavbarHover; ?>;
    background-color: <?php echo $backgroundNavbarHover; ?>;
}

 /* put the same color as in left vertical status */
.lnavbar {
    overflow: hidden;
    background-color: <?php echo $backgroundNavbar; ?>;
}

/* Expert menus */
.mainnav {
    display: inline-block;
    list-style: none;
    padding: 0;
    margin: 0 auto;
    width: 100%;
    background: <?php echo $backgroundNavbar; ?>;
    overflow: hidden;
}

.dropdown {
    position: absolute;
    width: 170px;
    opacity: 0;
    visibility: hidden;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}

.mainnav ul {
    padding: 0;
    list-style: none;
}

.mainnav li {
    display: block;
    float: left;
    font-size: 0;
    margin: 0;
    background: <?php echo $backgroundNavbar; ?>;
}

.mainnav li a {
    list-style: none;
    padding: 0;
    display: inline-block;
    padding: 1px 10px;
    font-family : verdana, arial, sans-serif;
    font-size: 14px;
    
    color: <?php echo $textNavbar; ?>;
    text-align: center;
    text-decoration: none;
}

.mainnav .has-subs a:after {
    content: "\f107";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-left: 1em;
}

.mainnav .has-subs .dropdown .subs a:after {
    content: "";
}

.mainnav li:hover {
    background: <?php echo $backgroundNavbarHover; ?>;
}

.mainnav li:hover a {
    color: <?php echo $textNavbarHover; ?>;
    background-color: <?php echo $backgroundNavbarHover; ?>;
}

/* First Level */
.subs {
    position: relative;
    top: 14px;
    width: 170px;
}

.has-subs:hover .dropdown,
.has-subs .has-subs:hover .dropdown {
    opacity: 1;
    visibility: visible;
}

.mainnav ul li,
.mainav ul li ul li  a {
    color: <?php echo $textDropdown; ?>;
    background-color: <?php echo $backgroundDropdown; ?>;
}

.mainnav li:hover ul a,
.mainnav li:hover ul li ul li a {
    color: <?php echo $textDropdown; ?>;
    background-color: <?php echo $backgroundDropdown; ?>;
}

.mainnav li ul li:hover,
.mainnav li ul li ul li:hover {
    background-color: <?php echo $backgroundDropdownHover; ?>;
}

.mainnav li ul li:hover a,
.mainnav li ul li ul li:hover a {
    color: <?php echo $textDropdownHover; ?>;
    background-color: <?php echo $backgroundDropdownHover; ?>;
}

.mainnav .has-subs .dropdown .has-subs a:after {
    content: "\f105";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-left: 1em;
}

/* Second Level */
.has-subs .has-subs .dropdown .subs {
    position: relative;
    top: -10px;
    width: 170px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}

.has-subs .has-subs .dropdown .subs a:after {
    content:"";
}

.has-subs .has-subs .dropdown {
    position: absolute;
    width: 170px;
    left: 170px;
    top: 0px;
    opacity: 0;
    visibility: hidden;
}

.menuconfig .menuadmin .menudashboard .menuupdate .menuupgrade .menupower .menulogs .menubackup .menuexpert .menureset {
    position: relative;
}

.menuconfig:before {
    content: "\f1de";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menuadmin:before {
    content: "\f2bd";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menuupdate:before {
    content: "\f021";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menuupgrade:before {
    content: "\f1b8";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menupower:before {
    content: "\f011";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menulogs:before {
    content: "\f06e";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menudashboard:before {
    content: "\f0e4";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menubackup:before {
    content: "\f187";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menuexpert:before {
    content: "\f0a3";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

.menureset:before {
    content: "\f1cd";
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
    padding-right: 0.2em;
}

